### ISSUE TITLE
Full path

### ISSUE THREAD

**Issue by dchinmay2** [asyncmash/roundy#1]
Very cute theme! Can you add an option to show the full cwd?

**Comment by nullxception** [comment]
Yeah, also I've been thinking about option for fish-like cwd too

**Comment by dchinmay2** [comment]
> fish-like cwd

wdym?

**Comment by nullxception** [comment]
> > fish-like cwd
> 
> wdym?

It's like default fish-shell. for example : `/etc/http/conf/extra` became `/e/h/c/extra`.
Just for an another option
